name: dart_server_grpc_demo
description: Dart gRPC sample command-line demo server
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  async: ^2.11.0
  grpc: ^3.2.4
  protobuf: ^3.1.0    

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
